<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PrinterOrderLogModel extends BaseModel
{

    //订单状态
    //0:未支付
    //10:已支付(打印中),
    //20:打印完成(送货中),
    //30:已接收
    //-1 已取消
    const STATUS_0 = 0;
    const STATUS_10 = 10;
    const STATUS_20 = 20;
    const STATUS_30 = 30;
    const STATUS_CANCEL = -1;

    protected $table = 'printer_order_log';

    protected $fillable = ['order_id','order_status','user_id'];


    public function createParam($orderID, $orderStatus, $userID) {

        $data = ['order_id' => $orderID, 'order_status' => $orderStatus, 'user_id' => $userID];
        $validator = \Validator::make($data, [
            'order_id' => ['required'],
            'order_status' => ['required'],
            'user_id' => ['required'],
        ]);
        $this->setCreateValidator($validator);

        return parent::create($data); // TODO: Change the autogenerated stub
    }

}
