<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PrintOrderItemModel extends BaseModel
{
    //

    protected $table = 'printer_order_item';

    protected $fillable = ['order_id', 'document_id', 'amount'];

    public function createParam( $orderID, $documentID, $amount)
    {
        $data = [
            'order_id' => $orderID,
            'document_id' => $documentID,
            'amount' => $amount,
        ];
        $validator = \Validator::make($data, [
            'order_id' => ['required'],
            'document_id' => ['required'],
            'amount' => ['required']
        ]);
        $this->setCreateValidator($validator);

        $rs = parent::create($data); // TODO: Change the autogenerated stub
        return $rs;
    }


}
